# Generated by Django 3.2.8 on 2021-11-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('hora_registro', models.TimeField(auto_now_add=True, verbose_name='Hora Registro')),
                ('status', models.BooleanField(default=True)),
                ('descripcion', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='medioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('hora_registro', models.TimeField(auto_now_add=True, verbose_name='Hora Registro')),
                ('status', models.BooleanField(default=True)),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('hora_registro', models.TimeField(auto_now_add=True, verbose_name='Hora Registro')),
                ('status', models.BooleanField(default=True)),
                ('nroruc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nro Ruc')),
                ('nombre', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nombre')),
                ('correo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Correo')),
                ('ctadetraccion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cta Detracción')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appman.mediopago', verbose_name='Medio Pago')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedorRucSap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('hora_registro', models.TimeField(auto_now_add=True, verbose_name='Hora Registro')),
                ('status', models.BooleanField(default=True)),
                ('ruc_sap', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ruc Sap')),
                ('proveedor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='appman.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('hora_registro', models.TimeField(auto_now_add=True, verbose_name='Hora Registro')),
                ('status', models.BooleanField(default=True)),
                ('contador', models.IntegerField(blank=True, null=True)),
                ('ruc_sap', models.CharField(blank=True, max_length=10, null=True)),
                ('sociedad', models.CharField(blank=True, max_length=10, null=True)),
                ('nrdocumento', models.CharField(blank=True, max_length=12, null=True)),
                ('cd', models.CharField(blank=True, max_length=10, null=True)),
                ('nrodocumento', models.CharField(blank=True, max_length=100, null=True)),
                ('importe', models.CharField(blank=True, max_length=100, null=True)),
                ('descuento', models.CharField(blank=True, max_length=100, null=True)),
                ('neto', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='appman.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('hora_registro', models.TimeField(auto_now_add=True, verbose_name='Hora Registro')),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appman.marca')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marcados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('hora_registro', models.TimeField(auto_now_add=True, verbose_name='Hora Registro')),
                ('status', models.BooleanField(default=True)),
                ('contador', models.IntegerField(blank=True, null=True)),
                ('sociedad', models.CharField(blank=True, max_length=10, null=True)),
                ('asignacion', models.CharField(blank=True, max_length=12, null=True)),
                ('nroorden', models.CharField(blank=True, max_length=12, null=True)),
                ('fechacontable', models.CharField(blank=True, max_length=10, null=True)),
                ('cd', models.CharField(blank=True, max_length=10, null=True)),
                ('nrodocumento', models.CharField(blank=True, max_length=12, null=True)),
                ('fechadocumento', models.CharField(blank=True, max_length=10, null=True)),
                ('div', models.CharField(blank=True, max_length=4, null=True)),
                ('moneda', models.CharField(blank=True, max_length=5, null=True)),
                ('neto', models.FloatField(blank=True, default=0, null=True)),
                ('descuento', models.FloatField(blank=True, default=0, null=True)),
                ('importe', models.FloatField(blank=True, default=0, null=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('concepto', models.CharField(blank=True, max_length=100, null=True)),
                ('viapago', models.CharField(blank=True, max_length=12, null=True)),
                ('nroruc', models.CharField(blank=True, max_length=11, null=True)),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('anotacion', models.CharField(blank=True, max_length=50, null=True)),
                ('proveedor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='appman.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='marca',
            name='mediopago',
            field=models.ManyToManyField(to='appman.medioPago', verbose_name='medios de pago'),
        ),
    ]
