# Generated by Django 3.2.8 on 2021-11-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='mediopago',
        ),
        migrations.AddField(
            model_name='marca',
            name='mediopago',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='appman.mediopago', verbose_name='Medio Pago'),
            preserve_default=False,
        ),
    ]
