# Generated by Django 3.2.8 on 2021-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appman', '0002_auto_20211111_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='mediopago',
        ),
        migrations.AddField(
            model_name='marca',
            name='mediopago',
            field=models.ManyToManyField(to='appman.medioPago', verbose_name='medios de pago'),
        ),
    ]
